### ISSUE TITLE
window.require is not a function

### ISSUE THREAD

**Issue by koenoe** [hardchor/electron-redux#155]
After updating the package from 1.4.0 to 1.5.1 I get the error `window.require is not a function`.
Haven't changed anything in my code.

![](https://i.imgur.com/yVq9S0m.jpg)

Windows 10
Electron 8.2.4
Typescript 3.8.2

I just use TSC to compile to Javascript, not using Webpack or anything.

Looks like this commit is the culprit: https://github.com/hardchor/electron-redux/commit/a1ba87b107e36cfb0004ae0c5f5f07720d23e92b

**Comment by hardchor** [comment]
That was introduced in https://github.com/hardchor/electron-redux/pull/134.
@pellejacobs any idea why that is?

**Comment by hardchor** [comment]
@koenoe what happens when you set

```
new BrowserWindow({
  webPreferences: {
    nodeIntegration: true
  }
});
```

**Comment by koenoe** [comment]
> @koenoe what happens when you set
> 
> ```
> new BrowserWindow({
>   webPreferences: {
>     nodeIntegration: true
>   }
> });
> ```

Can give it a try later to see what happens, but it wouldn’t be a safe solution 😔

**Comment by hardchor** [comment]
Appreciate, just want to find a solution that works for everyone

**Comment by koenoe** [comment]
It works fine with `nodeIntegration` enabled :-)

**Comment by hardchor** [comment]
@koenoe I decided to roll those changes back in 1.5.2. We'll need to find another solution for webpack.

Could you check if that fixes the issue for you, please?

**Comment by koenoe** [comment]
> @koenoe I decided to roll those changes back in 1.5.2. We'll need to find another solution for webpack.
> 
> Could you check if that fixes the issue for you, please?

Yes, this is working fine for me now in 1.5.2! Thank you.
